### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by verticeds** [Paybook/lite-python#4]
se instalo la instancia, al correrlo y crear el usuario desde web no guardaba los cambios en la BD, se dio de alta el usuario directamente en la base de datos.
al ingresar nuevamente a la aplicación, acepta el usuario pero al ingresar al apartado de transacciones, nos saca de la aplicación y vuelve a pedir usuario y contraseña. 
en el log aparece lo siguiente

<img width="490" alt="image" src="https://user-images.githubusercontent.com/62068813/85912323-53412100-b7f1-11ea-8869-370297ed3fda.png">

<img width="407" alt="image" src="https://user-images.githubusercontent.com/62068813/85912333-6653f100-b7f1-11ea-8510-df9f530d278e.png">

gracias

**Comment by aldoea** [comment]
Hola @verticeds !

Se esta creando el archivo paybook.db al correr la instancía ?
Cuando logran inciar sesión con el usuario ingresado directamente en la base de datos, el Widget en cuentas se despliega correctamente ?

**Comment by aldoea** [comment]
Hola @verticeds !

Se esta creando el archivo paybook.db al correr la instancía ?
Cuando logran inciar sesión con el usuario ingresado directamente en la base de datos, el Widget en cuentas se despliega correctamente ?

¡Saludos!

**Comment by verticeds** [comment]
Hola 
si se crea el archivo paybook.db.
no, no se despliega el widget
saludos

**Comment by aldoea** [comment]
Esto se puede deber a que la aplicación no está creando un token de sesión.
Puedes intentar borrar el archivo paybook.db, volver a instalar los requerimientos: `pip install -r requirements.txt` y levantar nuevamente la instancia `python main.py -a <YOUR_PAYBOOK_API_KEY>`.

No debería de haber mayor problema para hacer signup y login.

Saludos.

**Comment by verticeds** [comment]
volvi a instalar los requerimientos y ya funciono
Gracias

**Comment by aldoea** [comment]
Gracias a ti. 👍 
¡Saludos!
